version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.3.0
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    volumes:
      - ~/compose/seata/config:/root/seata-config
    environment:
      - SEATA_IP=192.168.1.167
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry

networks:
  default:
    external:
      name: service