server:
  port: 8861
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false #默认为true把调用链路收敛了，没有去维护；设置为false，让它维护