spring:
  profiles:
    active: dev
  application:
    name: stock-seata
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8071

# 设置mybatis
mybatis:
  #  config-location: classpath:mybatis-config.xml
  # 注意mapper-locations这里路径的写法，需要跟idea中的保持一致
  mapper-locations: classpath:com.github.mapper/*Mapper.xml
  type-aliases-package: com.github.model
  configuration:
    map-underscore-to-camel-case: false
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seata_server?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
logging:
  level:
    com.github: debug