version: "3"
services:
  nacos8849:
    hostname: nacos8849
    container_name: nacos8849
    image: nacos/nacos-server
    volumes:
      - ./cluster-logs/nacos8849:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
      - "9848:9848"
      - "9555:9555"
    env_file:
      - env/nacos-hostname.env
  nacos8850:
    hostname: nacos8850
    container_name: nacos8850
    image: nacos/nacos-server
    volumes:
      - ./cluster-logs/nacos8850:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
      - "9849:9848"
    env_file:
      - env/nacos-hostname.env
  nacos8851:
    hostname: nacos8851
    container_name: nacos8851
    image: nacos/nacos-server
    volumes:
      - ./cluster-logs/nacos8851:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8851:8848"
      - "9850:9848"
    env_file:
      - env/nacos-hostname.env

networks:
  default:
    external:
      name: service