spring:
  profiles:
    active: dev
  application:
    name: alibaba-order-seata
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 本地nacos集群地址
        server-addr: localhost:8847
        username: nacos
        password: nacos
    alibaba:
      seata:
        # 事务分组
        tx-service-group: my_test_tx_group
server:
  port: 8074
seata:
  # 设置seata的注册中心,告诉seata client怎么与seata server（TC）通讯（在springboot2.1之前只能通过registry.conf文件配置，即与seata的相同的registry.conf复制到微服务的resources目录中一份）
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8847 # 这就是seata server（TC）所在的nacos服务地址
      username: nacos
      password: nacos
      application: seata-server # 这就是seata server（TC）的服务名称，默认seata-server，如果未修改可以不配
      group: SEATA_GROUP # 这就是seata server（TC）所在的组，默认SEATA_GROUP，如果未修改可以不配
  # 还需要设置seata的配置中心，可以读取到nacos中配置列表中关于client*的配置项
  config:
    type: nacos
    nacos:
      server-addr: localhost:8847
      username: nacos
      password: nacos
      group: SEATA_GROUP
# 设置mybatis
mybatis:
  #  config-location: classpath:mybatis-config.xml
  # 注意mapper-locations这里路径的写法，需要跟idea中的保持一致
  mapper-locations: classpath:com.github.mapper/*Mapper.xml
  type-aliases-package: com.github.model
  configuration:
    map-underscore-to-camel-case: false
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
logging:
  level:
    com.github: debug