server:
  port: 8040

spring:
  application:
    # nacos会把应用名称当作服务名称
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
# springboot的默认日志级别是info，feign的debug日志不会打印
logging:
  level:
    # 只设置com.github.feign包下面的接口日志打印
    com.github.feign: debug
