server:
  port: 8040

spring:
  application:
    # nacos会把应用名称当作服务名称
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
# springboot的默认日志级别是info，feign的debug日志不会打印
logging:
  level:
    # 只设置com.github.feign包下面的接口日志打印
    com.github.feign: debug
# 通过配置文件，修改feign的日志级别
feign:
  client:
    config:
      # 配置调用product-service的接口日志级别为BASIC，输出内容会少于stock-service的debug的级别
      product-service:
        loggerLevel: BASIC
        # 设置为feign默认的契约，还原成原生注解，老版本升级的时候使用
        #contract: feign.Contract.Default
        # 连接超时时间，默认2s
        connectTimeout: 5000
        # 请求处理超时时间，默认5s
        readTimeout: 5000
        # 配置自定义feign拦截器
        requestInterceptors[0]: com.github.interceptor.CustomFeignInterceptor
