version: "3"
services:
  mysql:
    image: mysql:5
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
    #      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
networks:
  default:
    external:
      name: service